version: "3"
services:

  mindwiki-dev:
    build: .
    environment:
      DEBUG: "True"
      DATA_DIR: "/var/lib/mindwiki/"
    ports:
      - "8080:1312"
    volumes:
      - ./:/usr/src/mindwiki
      - /tmp/mindwiki:/var/lib/mindwiki
