version: "3"
services:

  mindwiki:
    build: .
    environment:
      DATABASE_DIR: "/var/lib/mindwiki/"
    ports:
      - "1312:1312"
    volumes:
      - ./:/usr/src/mindwiki
      - ~/.local/share/mindwiki:/var/lib/mindwiki
