# Generated by Django 4.0.4 on 2022-06-06 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=64)),
                ('body', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mindwiki.page')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('mindwiki.page',),
        ),
        migrations.CreateModel(
            name='WebLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('tags', models.ManyToManyField(to='mindwiki.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='page',
            name='tags',
            field=models.ManyToManyField(to='mindwiki.tag'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('data', models.ImageField(upload_to='images')),
                ('description', models.TextField(blank=True)),
                ('tags', models.ManyToManyField(to='mindwiki.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('data', models.FileField(upload_to='files')),
                ('description', models.TextField(blank=True)),
                ('tags', models.ManyToManyField(to='mindwiki.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mindwiki.page')),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(
                    choices=[('NS', 'Not Started'), ('IP', 'In Progress'),
                             ('B', 'Blocked'), ('C', 'Closed')], default='NS',
                    max_length=3)),
                ('status_line', models.CharField(blank=True, max_length=256)),
                ('pages', models.ManyToManyField(blank=True,
                                                 related_name='project_pages',
                                                 to='mindwiki.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('mindwiki.page',),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('tag_ptr', models.OneToOneField(auto_created=True,
                                                 on_delete=django.db.models.deletion.CASCADE,
                                                 parent_link=True,
                                                 primary_key=True,
                                                 serialize=False,
                                                 to='mindwiki.tag')),
                ('tags', models.ManyToManyField(related_name='category_tags',
                                                to='mindwiki.tag')),
            ],
            bases=('mindwiki.tag',),
        ),
    ]
